name: Notify Discord on Push

on: [push]

jobs:
  discordNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send embed message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          COMMIT_MESSAGE=$(jq -r '.head_commit.message' < $GITHUB_EVENT_PATH)
          COMMIT_URL=$(jq -r '.head_commit.url' < $GITHUB_EVENT_PATH)
          REPO_NAME=$(jq -r '.repository.full_name' < $GITHUB_EVENT_PATH)
          AUTHOR_NAME=$(jq -r '.head_commit.author.name' < $GITHUB_EVENT_PATH)
          AUTHOR_AVATAR=$(jq -r '.sender.avatar_url' < $GITHUB_EVENT_PATH)
          TIMESTAMP=$(jq -r '.head_commit.timestamp' < $GITHUB_EVENT_PATH)

          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
                "embeds": [
                  {
                    "title": "Update in Dev Version",
                    "description": "## '"$COMMIT_MESSAGE"'",
                    "url": "'"$COMMIT_URL"'",
                    "timestamp": "'"$TIMESTAMP"'",
                    "author": {
                      "name": "'"$AUTHOR_NAME"'",
                      "icon_url": "'"$AUTHOR_AVATAR"'"
                    },
                    "color": 5814783
                  }
                ]
              }' \
          $DISCORD_WEBHOOK_URL