name: Notify Discord on Push

on: [push]

jobs:
  discordNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          COMMIT_MESSAGE=$(jq -r '.head_commit.message' < $GITHUB_EVENT_PATH)
          COMMIT_URL=$(jq -r '.head_commit.url' < $GITHUB_EVENT_PATH)
          REPO_NAME=$(jq -r '.repository.full_name' < $GITHUB_EVENT_PATH)

          # Format the message as plain text
          MESSAGE="**${COMMIT_MESSAGE}**\n- # [Learn more](${COMMIT_URL})"

          # Send message to Discord
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"$MESSAGE\"}" \
          $DISCORD_WEBHOOK_URL